-- Blue Beacon Research: Production Database Schema

-- 1. Profiles Table (Linked to Auth Users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  plan_tier TEXT DEFAULT 'free', -- 'free', 'analyst', 'pro', 'api'
  onboarding_completed BOOLEAN DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Users can view their own profile" ON public.profiles 
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" ON public.profiles 
  FOR UPDATE USING (auth.uid() = id);

-- 2. Signals Table (Tactical Market Intelligence)
CREATE TABLE IF NOT EXISTS public.signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  severity INTEGER CHECK (severity >= 1 AND severity <= 10) NOT NULL,
  confidence FLOAT CHECK (confidence >= 0 AND confidence <= 1) NOT NULL,
  country TEXT,
  region TEXT,
  sources_count INTEGER DEFAULT 1,
  is_breaking BOOLEAN DEFAULT false,
  is_active BOOLEAN DEFAULT true,
  commodity_impacts JSONB DEFAULT '[]'::jsonb, -- Array of { asset, direction, confidence }
  event_type TEXT, -- 'CIVIL_UNREST', 'ARMED_CONFLICT', etc.
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;

-- Policies for Signals
CREATE POLICY "Anyone can view active signals" ON public.signals 
  FOR SELECT USING (is_active = true);

-- 3. Waitlist Table (Access Control)
CREATE TABLE IF NOT EXISTS public.waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  full_name TEXT,
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- Policies for Waitlist
CREATE POLICY "Users can view their own waitlist entry" ON public.waitlist 
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can join the waitlist" ON public.waitlist 
  FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- 4. Commodities Table (Reference Data)
CREATE TABLE IF NOT EXISTS public.commodities (
  id TEXT PRIMARY KEY, -- 'OIL', 'GOLD', etc.
  name TEXT NOT NULL,
  category TEXT,
  is_active BOOLEAN DEFAULT true
);

-- Enable RLS
ALTER TABLE public.commodities ENABLE ROW LEVEL SECURITY;

-- Policies for Commodities
CREATE POLICY "Anyone can view active commodities" ON public.commodities 
  FOR SELECT USING (is_active = true);
