import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Original custom properties for legacy compatibility
        surface_legacy: {
          DEFAULT: "var(--bg-primary)",
          secondary: "var(--bg-secondary)",
          elevated: "var(--bg-elevated)",
          app: "var(--bg-app)",
        },
        border_legacy: { DEFAULT: "var(--border)", subtle: "var(--border-subtle)" },
        text_legacy: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          subtle: "var(--accent-subtle)",
        },
        danger: { DEFAULT: "var(--danger)", subtle: "var(--danger-subtle)" },
        warning: { DEFAULT: "var(--warning)", subtle: "var(--warning-subtle)" },
        success: { DEFAULT: "var(--success)", subtle: "var(--success-subtle)" },
        price: { up: "var(--price-up)", down: "var(--price-down)" },
        
        // STITCH GENERATED EXACT TOKENS
        "inverse-surface": "#fcf8f8",
        "secondary": "#9c9f9b",
        "on-tertiary-fixed": "#444d2e",
        "primary-dim": "#3cd096",
        "surface-container-highest": "#262626",
        "on-error": "#490106",
        "surface": "#0e0e0e",
        "surface-variant": "#262626",
        "on-secondary-container": "#bdc0bc",
        "surface-dim": "#0e0e0e",
        "on-surface": "#e7e5e4",
        "on-primary-fixed-variant": "#006947",
        "on-secondary-fixed-variant": "#595c59",
        "tertiary": "#f4fed3",
        "background": "#0e0e0e",
        "outline-variant": "#484848",
        "primary-container": "#005236",
        "error": "#ee7d77",
        "secondary-fixed": "#e1e3df",
        "primary-fixed-dim": "#5fedb0",
        "surface-bright": "#2c2c2c",
        "on-tertiary-container": "#515a3a",
        "inverse-on-surface": "#565554",
        "surface-tint": "#4edea3",
        "surface-container-low": "#131313",
        "on-tertiary-fixed-variant": "#606a48",
        "error-container": "#7f2927",
        "tertiary-fixed-dim": "#dfeac0",
        "surface-container-high": "#202020",
        "secondary-dim": "#9c9f9b",
        "secondary-fixed-dim": "#d3d5d1",
        "on-secondary-fixed": "#3d403d",
        "on-error-container": "#ff9993",
        "on-secondary": "#1e211f",
        "inverse-primary": "#006d4a",
        "on-primary": "#004a31",
        "tertiary-container": "#e5f0c5",
        "surface-container": "#1a1919",
        "outline": "#767575",
        "on-primary-fixed": "#004930",
        "surface-container-lowest": "#000000",
        "on-surface-variant": "#acabaa",
        "tertiary-fixed": "#eef9cd",
        "on-tertiary": "#596342",
        "secondary-container": "#393c39",
        "error-dim": "#bb5551",
        "primary-fixed": "#6ffbbe",
        "tertiary-dim": "#dfeac0",
        "primary": "#4edea3",
        "on-background": "#e7e5e4",
        "on-primary-container": "#5ae9ac"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
