import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Original custom properties for legacy compatibility
        surface_legacy: {
          DEFAULT: "var(--bg-primary)",
          secondary: "var(--bg-secondary)",
          elevated: "var(--bg-elevated)",
          app: "var(--bg-app)",
        },
        border_legacy: { DEFAULT: "var(--border)", subtle: "var(--border-subtle)" },
        text_legacy: {
          primary: "var(--text-primary)",
          secondary: "var(--text-secondary)",
          muted: "var(--text-muted)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          hover: "var(--accent-hover)",
          subtle: "var(--accent-subtle)",
        },
        danger: { DEFAULT: "var(--danger)", subtle: "var(--danger-subtle)" },
        warning: { DEFAULT: "var(--warning)", subtle: "var(--warning-subtle)" },
        success: { DEFAULT: "var(--success)", subtle: "var(--success-subtle)" },
        price: { up: "var(--price-up)", down: "var(--price-down)" },
        
        // STITCH GENERATED EXACT TOKENS
        "inverse-primary": "#006c4a",
        "tertiary": "#ffdad7",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#7f2927",
        "on-tertiary-container": "#8e3432",
        "surface-container": "#201f1f",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#042100",
        "background": "#131313",
        "on-error": "#690005",
        "secondary-fixed": "#8efc67",
        "surface-container-low": "#1c1b1b",
        "on-tertiary": "#611213",
        "surface-tint": "#4edea3",
        "secondary-container": "#3ba615",
        "inverse-surface": "#e5e2e1",
        "on-secondary-container": "#093100",
        "on-secondary-fixed-variant": "#145200",
        "surface-container-highest": "#353534",
        "primary": "#6ffbbe",
        "inverse-on-surface": "#313030",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-high": "#2a2a2a",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#ffdad7",
        "tertiary-container": "#ffb3ad",
        "on-primary-fixed": "#002114",
        "primary-container": "#4edea3",
        "outline": "#86948a",
        "on-primary-container": "#005f40",
        "surface": "#131313",
        "secondary-fixed-dim": "#72df4d",
        "on-primary": "#003824",
        "outline-variant": "#3c4a42",
        "surface-bright": "#393939",
        "on-surface-variant": "#bbcac0",
        "secondary": "#72df4d",
        "error": "#ffb4ab",
        "primary-fixed": "#6ffbbe",
        "on-primary-fixed-variant": "#005236",
        "on-secondary": "#0b3900",
        "tertiary-fixed-dim": "#ffb3ae",
        "on-tertiary-fixed": "#410004",
        "primary-fixed-dim": "#4edea3"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Space Grotesk", "sans-serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
