import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";

// Password recovery gets its own client, deliberately configured for the implicit
// flow, separate from the shared PKCE client in lib/supabase.ts (@supabase/ssr's
// createBrowserClient hardcodes flowType: "pkce" and can't be overridden via
// options). PKCE requires the code_verifier generated by whichever browser called
// resetPasswordForEmail() to still be in that same browser's storage when the
// link is opened later -- which breaks whenever a real user opens the emailed
// link in a different browser/device/in-app browser (Gmail app, WhatsApp link
// preview, etc.) than the one that requested the reset. Implicit flow avoids
// that dependency: the tokens are self-contained in the link itself, so any
// browser can complete the flow. This is a deliberate choice for this app, not
// a universal fact about how Supabase recovery links work -- whichever flow the
// *sending* client uses is what GoTrue puts in the email link, so both the
// sender (forgot-password/page.tsx) and receiver (reset-password/page.tsx) must
// use this same client for the flow types to match end to end.
let cached: SupabaseClient | null = null;

export function getSupabaseRecoveryClient(): SupabaseClient | null {
  if (cached) return cached;
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anonKey) return null;
  cached = createClient(url, anonKey, {
    auth: { flowType: "implicit", detectSessionInUrl: true, persistSession: true },
  });
  return cached;
}
