import { createClient } from "@supabase/supabase-js";
import type { SupabaseClient } from "@supabase/supabase-js";

// Shared client for every auth flow that emails the user a link they might open in a
// different browser/device/in-app browser than the one that started the flow: password
// reset, signup email confirmation, and (if added later) magic links / invites / email
// changes. Deliberately configured for the implicit flow, separate from the shared PKCE
// client in lib/supabase.ts (@supabase/ssr's createBrowserClient hardcodes
// flowType: "pkce" and can't be overridden via options). PKCE requires the code_verifier
// generated by whichever browser/client started the flow to still be present when the
// link is opened later -- which breaks whenever a real user opens the emailed link
// somewhere else (Gmail app, WhatsApp link preview, a different device entirely).
// Implicit flow avoids that dependency: the tokens are self-contained in the link
// itself, so any browser can complete the flow.
//
// PKCE is still correct (and stays on the shared client) for flows that never leave a
// single browser session, like Google OAuth -- see apps/web/app/auth/callback/route.ts.
//
// Every page that *sends* one of these emails (forgot-password, signup, VerifyClient's
// resend) and every page that *receives* the resulting link (reset-password, confirm)
// must use this same client so the flow types match end to end -- that mismatch is
// exactly what caused the reset-password bug this was extracted from.
let cached: SupabaseClient | null = null;

export function getSupabaseEmailAuthClient(): SupabaseClient | null {
  if (cached) return cached;
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anonKey) return null;
  cached = createClient(url, anonKey, {
    auth: { flowType: "implicit", detectSessionInUrl: true, persistSession: true },
  });
  return cached;
}
